spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cc?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  mapper-locations:
  - classpath*mybatis/*xml